version: '3'

services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: on-failure

  redis:
    image: redis
    container_name: redis
    restart: on-failure

  dummy-api:
    build: ./dummy-microservices/dummy-api
    container_name: api
    restart: on-failure
    depends_on:
     - rabbitmq
     - dummy-storage
    ports:
      - 8080:8080
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  dummy-data-converter:
    build: ./dummy-microservices/dummy-data-converter
    container_name: data-converter
    restart: on-failure
    depends_on:
     - rabbitmq
     - dummy-storage
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  dummy-storage:
    build: ./dummy-microservices/dummy-storage
    container_name: storage
    restart: on-failure
    depends_on:
      - rabbitmq
      - redis
    environment:
      REDIS_URL: http://redis:6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672