version: '3'

services:
  vault-build:
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    build: .
    image: 0.0.0.0:5000/concvault:latest
    container_name: concvault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK

  vault:
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    image: 0.0.0.0:5000/concvault:latest
    container_name: concvault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK